export const services = [
  {
    name: "HTTP server",
    id: "http-server",
    type: "Transport",
    status: "Healthy",
    latency: "12 ms",
    uptime: "14d 6h",
    description: "Serves application routes and dashboard requests.",
    detail: "Listening on :8080. All readiness checks are passing.",
    load: 28,
  },
  {
    name: "PostgreSQL",
    id: "postgres",
    type: "Database",
    status: "Healthy",
    latency: "4 ms",
    uptime: "14d 6h",
    description: "Primary application database and connection pool.",
    detail: "18 of 100 connections in use. The latest query completed in 4 ms.",
    load: 18,
  },
  {
    name: "Redis",
    id: "redis",
    type: "Cache",
    status: "Degraded",
    latency: "148 ms",
    uptime: "14d 6h",
    description: "Shared cache and event coordination.",
    detail:
      "Latency exceeded the 100 ms threshold at 10:42. Check the connection pool and network path.",
    load: 84,
  },
  {
    name: "Event bus",
    id: "event-bus",
    type: "Messaging",
    status: "Healthy",
    latency: "2 ms",
    uptime: "14d 6h",
    description: "Dispatches events between application extensions.",
    detail: "No pending deliveries. All subscribers are connected.",
    load: 12,
  },
  {
    name: "Scheduler",
    id: "scheduler",
    type: "Worker",
    status: "Healthy",
    latency: "6 ms",
    uptime: "14d 6h",
    description: "Runs scheduled application jobs.",
    detail: "8 jobs registered. The next run is scheduled for 11:00.",
    load: 36,
  },
  {
    name: "Object storage",
    id: "storage",
    type: "Storage",
    status: "Healthy",
    latency: "24 ms",
    uptime: "14d 6h",
    description: "Stores application files and generated exports.",
    detail: "Bucket is accessible. Last write completed successfully.",
    load: 42,
  },
]
export const extensions = [
  {
    name: "Authsome",
    category: "Identity",
    description: "Authentication, sessions, and access policies.",
    version: "0.8.2",
    status: "Ready",
    icon: "auth",
  },
  {
    name: "Streaming",
    category: "Messaging",
    description: "Channels, connections, and message delivery.",
    version: "0.6.0",
    status: "Ready",
    icon: "stream",
  },
  {
    name: "Chronicle",
    category: "Observability",
    description: "Structured application events and audit records.",
    version: "0.4.1",
    status: "Ready",
    icon: "audit",
  },
  {
    name: "Warden",
    category: "Security",
    description: "Resource permissions and access decisions.",
    version: "0.5.0",
    status: "Ready",
    icon: "shield",
  },
  {
    name: "Vessel",
    category: "Infrastructure",
    description: "Background tasks and worker coordination.",
    version: "0.3.2",
    status: "Ready",
    icon: "box",
  },
  {
    name: "Relay",
    category: "Notifications",
    description: "Email delivery and notification providers.",
    version: "0.2.0",
    status: "Setup required",
    icon: "mail",
  },
]
export const activity = [
  {
    time: "10:48:32",
    event: "Session created",
    source: "Authsome",
    actor: "alex@acme.dev",
    status: "Success",
    id: "evt_9f12",
  },
  {
    time: "10:46:18",
    event: "Policy updated",
    source: "Warden",
    actor: "rex@acme.dev",
    status: "Success",
    id: "evt_9f11",
  },
  {
    time: "10:44:05",
    event: "Job completed",
    source: "Scheduler",
    actor: "system",
    status: "Success",
    id: "evt_9f10",
  },
  {
    time: "10:42:16",
    event: "Cache latency threshold exceeded",
    source: "Redis",
    actor: "health-check",
    status: "Warning",
    id: "evt_9f09",
  },
  {
    time: "10:40:51",
    event: "Channel created",
    source: "Streaming",
    actor: "alex@acme.dev",
    status: "Success",
    id: "evt_9f08",
  },
  {
    time: "10:38:07",
    event: "Access denied",
    source: "Warden",
    actor: "service:export",
    status: "Denied",
    id: "evt_9f07",
  },
  {
    time: "10:36:22",
    event: "Extension initialized",
    source: "Chronicle",
    actor: "system",
    status: "Success",
    id: "evt_9f06",
  },
]
export const routes = [
  {
    method: "GET",
    path: "/api/v1/users",
    owner: "Authsome",
    requests: "24,812",
    latency: "42 ms",
    status: "Healthy",
  },
  {
    method: "POST",
    path: "/api/v1/auth/login",
    owner: "Authsome",
    requests: "8,420",
    latency: "86 ms",
    status: "Healthy",
  },
  {
    method: "GET",
    path: "/api/v1/channels",
    owner: "Streaming",
    requests: "18,204",
    latency: "28 ms",
    status: "Healthy",
  },
  {
    method: "POST",
    path: "/api/v1/messages",
    owner: "Streaming",
    requests: "42,168",
    latency: "148 ms",
    status: "Degraded",
  },
  {
    method: "GET",
    path: "/health",
    owner: "Core",
    requests: "5,760",
    latency: "3 ms",
    status: "Healthy",
  },
  {
    method: "GET",
    path: "/api/v1/audit",
    owner: "Chronicle",
    requests: "1,204",
    latency: "32 ms",
    status: "Healthy",
  },
]
export const traces = routes.map((route, index) => ({
  ...route,
  id: `8fa2c0${index}d19`,
  time: `10:48:${32 - index * 3}`,
  duration: [42, 86, 28, 148, 3, 32][index]!,
  spans: [6, 9, 4, 12, 1, 5][index]!,
}))
