import { useState, type ComponentType } from "react"
import { Button, buttonVariants } from "@forge-go/dashboard-kit/components/button"
import { PageHeader } from "@forge-go/dashboard-kit/components/page-header"
import { QueryBoundary } from "@forge-go/dashboard-kit/components/query-boundary"
import { ResourceTable, type Column } from "@forge-go/dashboard-kit/components/resource-table"
import { Timestamp } from "@forge-go/dashboard-kit/components/timestamp"
import { PluginLink, useQuery } from "@forge-go/dashboard-plugin"
import type { PluginPageProps } from "@forge-go/dashboard-plugin"
import type { ReportListResponse, ReportSummary } from "../types"
import { formatSeq, reportTypeLabel } from "../format"

const PAGE = 50

const columns: Column<ReportSummary>[] = [
  {
    id: "title",
    header: "Report",
    cell: (r) => (
      <PluginLink to={`/reports/${encodeURIComponent(r.id)}`} className="font-medium">
        {r.title}
      </PluginLink>
    ),
  },
  { id: "id", header: "ID", cell: (r) => <span className="font-mono text-xs">{r.id}</span> },
  { id: "type", header: "Type", cell: (r) => reportTypeLabel(r.type) },
  {
    id: "period",
    header: "Period",
    cell: (r) => (
      <span className="whitespace-nowrap">
        <Timestamp value={r.period.from} label="period start" /> to <Timestamp value={r.period.to} label="period end" />
      </span>
    ),
  },
  { id: "by", header: "Generated by", cell: (r) => <span className="font-mono text-xs">{r.generatedBy}</span> },
  { id: "created", header: "Generated", cell: (r) => <Timestamp value={r.createdAt} label="generation time" /> },
]

export const ReportsPage: ComponentType<PluginPageProps> = () => {
  const [offset, setOffset] = useState(0)
  const q = useQuery<ReportListResponse>("reports.list", { limit: PAGE, offset })

  return (
    <section className="flex flex-col gap-4">
      <PageHeader
        title="Reports"
        description="Compliance reports generated from this scope's events, each with the integrity check that was run when it was generated."
        actions={
          <>
            <PluginLink to="/new-custom-report" className={buttonVariants({ variant: "outline" })}>
              Build a custom report
            </PluginLink>
            <PluginLink to="/new-report" className={buttonVariants()}>
              Generate a report
            </PluginLink>
          </>
        }
      />
      <QueryBoundary title="reports" query={q} skeletonRows={5}>
        {(data) => (
          <>
            <ResourceTable
              columns={columns}
              rows={data.reports}
              rowKey={(r) => r.id}
              caption={`${formatSeq(data.reports.length)} reports shown`}
              emptyMessage="No reports have been generated in this scope."
            />
            {/* The store keeps no count, so there is no "page 2 of N": only whether another page exists. */}
            <div className="flex justify-end gap-2">
              <Button variant="outline" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - PAGE))}>
                Previous page
              </Button>
              <Button variant="outline" disabled={!data.hasMore} onClick={() => setOffset(offset + PAGE)}>
                Next page
              </Button>
            </div>
          </>
        )}
      </QueryBoundary>
    </section>
  )
}
