import { useEffect, useState, type ComponentType } from "react"
import { Button } from "@forge-go/dashboard-kit/components/button"
import { DescriptionList } from "@forge-go/dashboard-kit/components/detail-layout"
import { PageHeader } from "@forge-go/dashboard-kit/components/page-header"
import {
  CommandAlert,
  QueryBoundary,
} from "@forge-go/dashboard-kit/components/query-boundary"
import { ResourceTable } from "@forge-go/dashboard-kit/components/resource-table"
import { StatGrid } from "@forge-go/dashboard-kit/components/stat-grid"
import { Timestamp } from "@forge-go/dashboard-kit/components/timestamp"
import {
  PluginLink,
  queryStore,
  useQuery,
  usePluginClient,
} from "@forge-go/dashboard-plugin"
import type { ContractError, PluginPageProps } from "@forge-go/dashboard-plugin"
import type {
  ExportReportResponse,
  ReportDetail,
  ReportSection,
} from "../types"
import { ReportVerification } from "../components/report-verification"
import { eventColumns } from "../components/event-columns"
import { TenantValue } from "../components/tenant"
import { saveFile } from "../download"
import { formatSeq, pageOf, reportTypeLabel } from "../format"

const FORMATS = [
  { format: "json", label: "Download JSON" },
  { format: "csv", label: "Download CSV" },
  { format: "markdown", label: "Download Markdown" },
  { format: "html", label: "Download HTML" },
] as const

const columns = eventColumns({ showUser: true })

export const ReportDetailPage: ComponentType<PluginPageProps> = ({
  params,
}) => {
  const id = params.id ?? ""
  const q = useQuery<ReportDetail>("reports.detail", { id })
  const download = useExport(id)

  return (
    <section className="flex min-w-0 flex-col gap-4">
      <PageHeader
        title={q.data?.title ?? "Report"}
        description="A compliance report as it was generated. Its events and its integrity check are a record of that moment."
        actions={
          <div className="flex flex-wrap items-center gap-2">
            {FORMATS.map((f) => (
              <Button
                key={f.format}
                variant="outline"
                disabled={download.busy}
                onClick={() => download.start(f.format)}
              >
                {f.label}
              </Button>
            ))}
          </div>
        }
      />
      <CommandAlert
        title="Could not export the report"
        error={download.error}
      />
      <QueryBoundary title="report" query={q} skeletonRows={6}>
        {(r) => (
          <div className="flex min-w-0 flex-col gap-4">
            <DescriptionList
              items={[
                {
                  term: "Report",
                  value: <span className="font-mono text-xs">{r.id}</span>,
                },
                { term: "Type", value: reportTypeLabel(r.type) },
                {
                  term: "Period",
                  value: (
                    <span>
                      <Timestamp value={r.period.from} label="period start" />{" "}
                      to <Timestamp value={r.period.to} label="period end" />
                    </span>
                  ),
                },
                {
                  term: "Tenant",
                  value: <TenantValue tenantId={r.tenantId} />,
                },
                {
                  term: "Generated by",
                  value: (
                    <span className="font-mono text-xs">{r.generatedBy}</span>
                  ),
                },
                {
                  term: "Generated",
                  value: (
                    <Timestamp value={r.createdAt} label="generation time" />
                  ),
                },
              ]}
            />
            {r.stats && (
              <StatGrid
                items={[
                  {
                    label: "Total events",
                    value: formatSeq(r.stats.totalEvents),
                  },
                  {
                    label: "Critical",
                    value: formatSeq(r.stats.criticalEvents),
                  },
                  { label: "Failed", value: formatSeq(r.stats.failedEvents) },
                  { label: "Denied", value: formatSeq(r.stats.deniedEvents) },
                ]}
              />
            )}
            {r.sections.map((s, i) => (
              <Section key={`${i}-${s.title}`} section={s} />
            ))}
            <ReportVerification report={r} />
            <PluginLink
              to="/reports"
              className="text-sm underline underline-offset-4"
            >
              Back to reports
            </PluginLink>
          </div>
        )}
      </QueryBoundary>
    </section>
  )
}

function Section({ section: s }: { section: ReportSection }) {
  return (
    <section className="flex min-w-0 flex-col gap-3">
      <h2 className="text-lg font-medium">{s.title}</h2>
      {s.notes && (
        <p className="max-w-prose text-sm whitespace-pre-line">{s.notes}</p>
      )}
      <ResourceTable
        columns={columns}
        rows={s.events}
        rowKey={(e) => e.id}
        caption={pageOf(
          s.events.length,
          s.matchedEvents,
          "matching event",
          "matching events"
        )}
        emptyMessage="No events matched this section."
      />
      {s.eventsTruncated && (
        <p className="text-sm font-medium">
          {`Showing ${formatSeq(s.events.length)} of ${formatSeq(s.matchedEvents)} matching events. The rest are counted here but are not listed in this report.`}
        </p>
      )}
    </section>
  )
}

/**
 * One export at a time. `reports.export` is a query, so it runs by turning on
 * an `enabled` flag, and it must run only on a click: an export fetched on
 * mount would build all four formats of every report anybody opened.
 */
function useExport(id: string) {
  const client = usePluginClient()
  const [format, setFormat] = useState<string | null>(null)
  const [error, setError] = useState<ContractError | undefined>()
  const q = useQuery<ExportReportResponse>(
    "reports.export",
    { id, format },
    { enabled: format !== null }
  )

  // A settled query is an external event this page has to answer: the file is
  // saved and the request is over. That is a state change with no other trigger.
  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(() => {
    if (format === null || q.loading) return
    if (q.data) {
      saveFile(q.data.filename, q.data.contentType, q.data.content)
      setFormat(null)
    } else if (q.error) {
      setError(q.error)
      setFormat(null)
    }
  }, [format, q.loading, q.data, q.error])
  /* eslint-enable react-hooks/set-state-in-effect */

  // The entry is one-shot. Left in the cache, the next click on the same
  // format would be served the previous file, or the previous failure, and
  // never ask the server again. This runs after the query has stopped being
  // watched, so the entry is dropped rather than re-issued.
  useEffect(() => {
    if (format === null)
      queryStore.invalidate(client.extension, ["reports.export"])
  }, [format, client])

  return {
    busy: format !== null,
    error,
    start: (f: string) => {
      setError(undefined)
      setFormat(f)
    },
  }
}
